//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrashAlarm.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrashAlarm.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutTabTitle {
            get {
                return ResourceManager.GetString("AboutTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to database.
        /// </summary>
        internal static string AddContactToDatabaseButtonTitle {
            get {
                return ResourceManager.GetString("AddContactToDatabaseButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string ContactsTabTitle {
            get {
                return ResourceManager.GetString("ContactsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is just little helper for people who had accident, fall down, are lost in nature or anything else. By simple command you can get to know your friends, your family or emergency numbers that something happen with you and provide them your location..
        /// </summary>
        internal static string CrashAlarmBodyInAbout {
            get {
                return ResourceManager.GetString("CrashAlarmBodyInAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crash Alarm app.
        /// </summary>
        internal static string CrashAlarmTitleInAbout {
            get {
                return ResourceManager.GetString("CrashAlarmTitleInAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteMeButtonTitle {
            get {
                return ResourceManager.GetString("DeleteMeButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter contact number.
        /// </summary>
        internal static string EnterContactNumberTitle {
            get {
                return ResourceManager.GetString("EnterContactNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        internal static string EnterNameTitle {
            get {
                return ResourceManager.GetString("EnterNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of contact.
        /// </summary>
        internal static string EnterTypeOfContact {
            get {
                return ResourceManager.GetString("EnterTypeOfContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help!.
        /// </summary>
        internal static string HelpButtonText {
            get {
                return ResourceManager.GetString("HelpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help message.
        /// </summary>
        internal static string HelpMessageTitle {
            get {
                return ResourceManager.GetString("HelpMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string HistoryTabTitle {
            get {
                return ResourceManager.GetString("HistoryTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrashAlarm App.
        /// </summary>
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string MainTabTitle {
            get {
                return ResourceManager.GetString("MainTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MapButtonTitle {
            get {
                return ResourceManager.GetString("MapButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My position.
        /// </summary>
        internal static string MyPositionString {
            get {
                return ResourceManager.GetString("MyPositionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTabTitle {
            get {
                return ResourceManager.GetString("SettingsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert to Emergency.
        /// </summary>
        internal static string SwitchAlertToEmergencyTitle {
            get {
                return ResourceManager.GetString("SwitchAlertToEmergencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert to Family.
        /// </summary>
        internal static string SwitchAlertToFamilyTitle {
            get {
                return ResourceManager.GetString("SwitchAlertToFamilyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert to Friends.
        /// </summary>
        internal static string SwitchAlertToFriendsTitle {
            get {
                return ResourceManager.GetString("SwitchAlertToFriendsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages were send. Number of messages: .
        /// </summary>
        internal static string ToastSendMessage {
            get {
                return ResourceManager.GetString("ToastSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to CrashAlarm app.
        /// </summary>
        internal static string WelcomeMessageOnMainPage {
            get {
                return ResourceManager.GetString("WelcomeMessageOnMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on Xamarin Forms and Prism.
        /// </summary>
        internal static string WelcomeMessageSecondLineOnMainPage {
            get {
                return ResourceManager.GetString("WelcomeMessageSecondLineOnMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location:.
        /// </summary>
        internal static string YourLocationLabel {
            get {
                return ResourceManager.GetString("YourLocationLabel", resourceCulture);
            }
        }
    }
}
